### ISSUE TITLE
Way to know the actual musical notes

### ISSUE THREAD

**Issue by Demfier** [gabolsgabs/DALI#2]
Hi,

Thank you for the wonderful dataset. I was wondering if there's a way to get the actual musical notes ('A', 'A#' etc.) from the current information. Right now, what I see in the `notes` section is a list of words from the lyrics. Maybe I am missing something, but it would be great if you could help me with this.

Thank you in advance.

-- Gaurav.

**Comment by gabolsgabs** [comment]
Hello Gaurav,

Thank you for your interest in DALI. About your demand. Yes, it's pretty easy to retrieve the `notes` information you are asking for. Let's start with the info we have:

```
entry = dali[uid]  # where uid is a unique id
notes = copy.deepcopy(entry.annotations['annot']['notes'])
print(notes[0])
{'text': 'some text',
 'freq': [523.2511306011972, 523.2511306011972],
 'time': [0.7719999999999999, 1.0719999999999998],
 'index': 0}
```
The `freq` key contains the note information in frequency. In the note level you have the same value for the two elements in the list. This is because internally I use a recursive function for transforming the horizontal level to vertical (and viceversa) that requires the same structure for each granularity level. Just take the first one.

If you want to find the musical note just transform the `freq` into MIDI notes as follow:

```
 def freq2note(freq):
    return np.round(12 * np.log2(freq/440.) + 69).astype(int)
```
Here's a example:
```
for i in notes:
    i['freq'][1] = freq2note(i['freq'][0])  # I stored in the second element in order to keep the vertical2horizontal functionality but feel free to store wherever you want
```

If you really want the note as you describe ('A', '#A', etc.), just create a hash table with the correlations as in [here](http://www.inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies)

Finally, keep in mind that there are some issues with the note information and sometimes they are wrong. We are working to solve these problems and there will be a new version of the dataset with these issues solved soon.

**Comment by Demfier** [comment]
Thank you @gabolsgabs !

**Comment by rynerisraid** [comment]
Hi,
Thank you for the wonderful dataset.
I found that the annotatioms of 'notes' missing through entry.annotations['annot']['notes']. 
I follow the tutorial, and execute the code  to entry.annotations['annot'], then the variable become entry.annotations['annot']['horizontal'], maybe some errors in my codes, could you give the executive processing in details.

Thanks,
Lin
